name: oidc-lab
services:
  - name: oidc-server
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: ISSUER
        scope: RUN_TIME
        value: ${oidc-server.PUBLIC_URL}
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
        value: change-me-to-a-random-string
      - key: SQLITE_PATH
        scope: RUN_TIME
        value: /app/data/oidc-lab.sqlite
